language: cpp

dist: trusty

compiler: gcc

addons:
  apt:
    packages:
    - gcc
    - make
    - libx11-dev
    - libxft-dev

script:
  - bash -C ./statcl.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true
  file:
    - statcl/WishDemo-x86_64.AppImage
    - statcl/statcl-files.txt
    - statcl/statcl-info.txt
    - statcl/statcl-logs.tar.gz
    - statcl/statcl-tcl-8.6.8.tar.gz
    - statcl/statcl-tk-8.6.8.tar.gz
    - statcl/statcl-tcllib-1.18.tar.gz
    - statcl/statcl-tklib-0.6.tar.gz
    - statcl/statcl-tkcon-2.7.1.tar.gz
